### ISSUE TITLE
[User feedback] Bug with VTG Enrollment

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-OCC-central-planning-reporting#10]
## dhis2

Username: jeverett@samaritan.org

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
- Platform: Win32

## User report
URL: https://cpr.samaritanspurse.org/api/apps/Central-Planning-Reporting/index.html#/country-grant

See the screen shot that shows this team (Diebougou) in Burkina Faso has VTG enrollment even though the 'Will VTG be needed' checkbox is not selected at neither the Team Grant nor the Country Template. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-162983236889631959.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/SP-OCC-central-planning-reporting/releases/tag/v0.0.7
